stages:
  - publish_image

job_publish_image:
  image: docker:latest
  variables:
    DOCKER_DRIVER: overlay2
    IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  services:
    - docker:dind
  stage: publish_image
  script:
    - docker login -u "gitlab-ci-token" -p "$CI_JOB_TOKEN" $CI_REGISTRY
    - docker build --pull --rm -t $IMAGE_TAG .
    - docker push $IMAGE_TAG
  only:
    - master
    - tags
  tags:
    - docker
