version: '3.7'
services:
  traefik:
    image: traefik:v2.2
    container_name: colosseum_www_traefik
    command:
      #- "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=true"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
  drupal:
    image: thp.sangre.fi:4999/colosseum/academy:master
    container_name: colosseum_www_drupal
    environment:
      TZ: "Europe/Helsinki"
      XDEBUG_CONFIG: remote_host=10.254.254.254
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: qwerty123
      MYSQL_DATABASE: drupal9_local
      THEME_DEBUG: "1"
      SITE_HASH_SALT: "7N3QzTKxf2FzvtPZiI9dhHQzFyXH91a4NWbRWZiC"
      REVERSE_PROXY_ENABLED: 1
      MODE: DEV
      STRIPE_SECRET_KEY: "sk_test_51HRYYeHBFfmt40OOwBgYflBkWQlIXnYI1tyD5AC8uVWl1PbbjO9L7mKRUAwBLH5x5gVQCY4cZ75njj2vCZFAHDI200zRFSgJ1t"
      STRIPE_PUBLIC_KEY: "pk_test_51HRYYeHBFfmt40OOH4UtXJDhwwBPVQXwdS91UL0AwabXcZ4mBhXGXRO1oszmeZ0ZCtqX9JWjdSvW73KXeR75aMwh00SVc1qAvd"
      STRIPE_WEBHOOK_SECRET: "whsec_28bwTBdYIhFFxuYTJj8wua6N51NVyYXK"
      REGISTRATION_ADMIN_EMAIL: "academy@colosseumdental.com"
    labels:
      - "traefik.http.routers.site.rule=Host(`col.localhost`)"
    volumes:
      - "site-files:/var/www/web/sites/default/files"
      - "./config-sync:/var/www/config-sync"
      - "./web/modules/custom:/var/www/web/modules/custom"
      - "./web/themes:/var/www/web/themes"
      - "./web/profiles:/var/www/web/profiles"
      - "./composer.json:/var/www/composer.json"
      - "./composer.lock:/var/www/composer.lock"
  mysql:
    container_name: colosseum_www_mysql
    image: library/mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: "qwerty123"
      MYSQL_DATABASE: "drupal9_local"
      MYSQL_PWD: "qwerty123"
      USER: "root"
      #TZ: "Europe/Helsinki"
    volumes:
      - "mysql:/var/lib/mysql"
    ports:
      - "33336:3306"

volumes:
  site-files:
    name: colosseum-website-files
  mysql:
    name: colosseum-website-mysql
